# Generated by Django 6.0.5 on 2026-05-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options_alter_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(auto_now_add=True)),
                ('user_name', models.CharField(max_length=100)),
                ('user_id', models.IntegerField(unique=True)),
                ('book_id', models.IntegerField(unique=True)),
                ('return_date', models.DateField()),
            ],
            options={
                'verbose_name': 'borrow',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='product',
            name='borrowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='format',
            field=models.CharField(choices=[('E-book', 'E-book'), ('Hardcopy', 'Hardcopy')], default='Hardcopy', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='language',
            field=models.CharField(default='English', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fantase', 'fantase'), ('romance', 'romance'), ('Action', 'Action'), ('History', 'History'), ('Religious', 'Religious'), ('Science', 'Science'), ('Horror', 'Horror'), ('Other', 'Other')], max_length=50),
        ),
    ]
